import { file, write } from 'bun';
import { readdir } from 'node:fs/promises';
import { join, relative } from 'node:path';

const UI_DIST = join(import.meta.dir, '../src/ui/dist');
const OUTPUT_FILE = join(import.meta.dir, '../src/server/assets.gen.ts');

async function getFiles(dir: string): Promise<string[]> {
    const dirents = await readdir(dir, { withFileTypes: true });
    const files = await Promise.all(dirents.map((dirent) => {
        const res = join(dir, dirent.name);
        return dirent.isDirectory() ? getFiles(res) : res;
    }));
    return Array.prototype.concat(...files);
}

console.log(`Building assets from ${UI_DIST}...`);

try {
    const files = await getFiles(UI_DIST);

    const assets: Record<string, string> = {};

    for (const filePath of files) {
        const relPath = relative(UI_DIST, filePath).replace(/\\/g, '/'); // Ensure forward slashes
        // We encode as Base64 to safely embed in TS source
        // Alternatively we can use Uint8Array literal but Base64 is cleaner for source file
        const content = await file(filePath).arrayBuffer();
        assets[relPath] = Buffer.from(content).toString('base64');
    }

    const code = `
// Auto-generated by scripts/embed-assets.ts
// Do not edit manually

export const assets: Record<string, string> = ${JSON.stringify(assets, null, 2)};

export function getAsset(path: string): Uint8Array | null {
  const b64 = assets[path] || assets['/' + path];
  if (!b64) return null;
  return Uint8Array.from(atob(b64), c => c.charCodeAt(0));
}
`;

    await write(OUTPUT_FILE, code);
    console.log(`Successfully embedded ${Object.keys(assets).length} files into ${OUTPUT_FILE}`);

} catch (e) {
    console.error('Error embedding assets. Did you run "npm run build" in src/ui?');
    console.error(e);
}
